import paramiko
ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
ssh.connect('novelove.jp', username='root', password='#Dama0228', timeout=15)
i,o,e = ssh.exec_command('cd /home/kusanagi/scripts && git reflog -n 10')
o.channel.recv_exit_status()
print('=== reflog ===')
print(o.read().decode())
i,o,e = ssh.exec_command('cd /home/kusanagi/scripts && git log --oneline -n 5')
o.channel.recv_exit_status()
print('=== current log ===')
print(o.read().decode())
i,o,e = ssh.exec_command('ls -la /home/kusanagi/scripts/novelove.log')
o.channel.recv_exit_status()
print('=== log perms ===')
print(o.read().decode())
ssh.close()
