import paramiko
ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
ssh.connect('novelove.jp', username='root', password='#Dama0228', timeout=15)
i,o,e = ssh.exec_command('curl -s -I http://novelove.jp/nexus/')
o.channel.recv_exit_status()
print('=== 外部からのアクセス (Nginx経由) ===\n' + o.read().decode())
i,o,e = ssh.exec_command('curl -s -I -u "admin:#Dama0228" http://127.0.0.1:8501/nexus/')
o.channel.recv_exit_status()
print('=== 内部ダッシュボードの稼働確認 (パスワード認証後) ===\n' + o.read().decode())
i,o,e = ssh.exec_command('ps aux | grep auto_post')
o.channel.recv_exit_status()
print('=== 実行中の自動投稿プロセス ===\n' + o.read().decode())
ssh.close()
