import paramiko
ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
ssh.connect('novelove.jp', username='root', password='#Dama0228', timeout=15)
i,o,e = ssh.exec_command('cd /home/kusanagi/scripts && git diff 0527ea9 a68b43e --stat')
o.channel.recv_exit_status()
print('=== diff stat ===')
print(o.read().decode())
i,o,e = ssh.exec_command('cd /home/kusanagi/scripts && git diff 0527ea9 a68b43e -- auto_post.py')
o.channel.recv_exit_status()
print('=== auto_post diff ===')
print(o.read().decode()[-5000:])
ssh.close()
